name: deploy static php site

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_to_server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # This step deploys the files from the repo to the server with SSH deploy (https://github.com/marketplace/actions/ssh-deploy)
      - name: deploy to server 📤
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # use secrets for deployment (https://docs.github.com/en/actions/security-guides/encrypted-secrets)
          ARGS: --delete
          SOURCE: "dist/" # use the origin of the php main file here (follows repo structure)
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/"

      # Runs a set of commands using the runners shell (or maybe send notification to discord, etc.)
      - name: deploy finished ✅
        run: echo "check if build was deployed to server"
